### PR TITLE
Socket virtual functions

### PR DESCRIPTION
**Pull request by lucaszanella**
Complement to https://github.com/xia-chu/ZLMediaKit/pull/468. Makes it possible to override all `Socket` functions.

### CODE REVIEW

**Comment by xia-chu** [comment]
I looked at your code and felt that the implementation was a little complicated. I think there is a better way to achieve the same function。
How about make the `Socket` constructor private and passing a `Socket factory` object to `TcpClient`?

The `Socket factory` can create an Socket subcalss, which implemented it's parent class's virtual method.

**Comment by lucaszanella** [comment]
Wouldn't making `Socket` constructor private mess with people that might already be using ZLToolKit for other purposes?

**Comment by xia-chu** [comment]
> Wouldn't making `Socket` constructor private mess with people that might already be using ZLToolKit for other purposes?

Well, you're right,  `making Socket constructor private ` is not a good way.
I plan to privatize the `Socket constructor` first, and then complete the transformation of the code, and then compile and run normally.
At last, I will make  `Socket` constructors public.

**Comment by lucaszanella** [comment]
> I plan to privatize the Socket constructor first, and then complete the transformation of the code, and then compile and run normally.

At last, I will make Socket constructors public.

I dont get what you proposed.

Also, I think there's no way to do it without virtual functions, because a pointer to a socket must be passed to ZLMediaKit. It can only work with virtual functions.

**Comment by xia-chu** [comment]
I will merge your code in these some days, but some changes will be made in some places. zltoolkit will merge most of them,
However, due to the relatively large changes to the interface of zlmediakit, I may not merge most of the changes to zlmediakit, I'm sorry.
Anyway, I'll meet your needs, it's just not like what you did

**Comment by lucaszanella** [comment]
No problem, I'll be happy with whatever solution you come with, thank you so much :+1:

**Pull request merged**
